const config = {
  NAME: 'N.exchange',
  DOMAIN: 'https://n.exchange',
  API_BASE_URL: 'https://api.n.exchange/en/api/v1',
  SUPPORT_EMAIL: 'support@n.exchange',
  PRICE_FETCH_INTERVAL: 60000,
  ORDER_BOOK_FETCH_INTERVAL: 10000,
  ORDER_DETAILS_FETCH_INTERVAL: 20000,
  RECENT_ORDERS_INTERVAL: 20000,
  RECENT_ORDERS_COUNT: 11,
  PRICE_COMPARISON_INTERVAL: 60000,
  REFERRAL_CODE: null,
  KYC_DETAILS_FETCH_INTERVAL: 20000,
  ADVANCED_MODE_ENABLED: true,
  POPULAR_COINS: ["BTC", "BCH", "ETH", "USD", "USDT", "EUR", "LTC", "XLM", "XRP"]
};

export default config;
